"""empty message

Revision ID: 1abc4ee1d048
Revises: c1a53bcc8445
Create Date: 2021-01-13 02:11:20.612639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abc4ee1d048'
down_revision = 'c1a53bcc8445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'price',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
