"""empty message

Revision ID: 8837a4753048
Revises: bf1010942803
Create Date: 2021-01-13 01:57:43.741173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8837a4753048'
down_revision = 'bf1010942803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'pudblished_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'pudblished_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
