"""empty message

Revision ID: c1a53bcc8445
Revises: 8837a4753048
Create Date: 2021-01-13 02:03:39.261878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a53bcc8445'
down_revision = '8837a4753048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'pudblished_at',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'pudblished_at',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
